### ISSUE TITLE
Installation des capteurs de distance sur le poteau central

### ISSUE THREAD

**Issue by whatthelock** [F-C-A/ENTRE-FUNGUS#20]
GanttStart: 2023-03-14
GanttDue: 2023-03-17

**Comment by DominicRoberts513** [comment]
nous allons probablement changer les capteur TOF pour des pour des capteur de voiture (proximité), leurs installation va donc changer

**Comment by Elwin-Durand** [comment]
Issue closed parce que les capteurs marchent et sont installés mais nous allons changer de capteurs
