### ISSUE TITLE
Gerer le branchement entre les different modules

### ISSUE THREAD

**Issue by whatthelock** [F-C-A/ENTRE-FUNGUS#21]
GanttStart: 2023-02-13
GanttDue: 2023-03-17

**Comment by DominicRoberts513** [comment]
problème, les sorties du module de cr34te 8 node pour contrôler les lumières sont des connecteurs 4 broches et les connecteurs des fixtures adressables ont 5 broches. Nous allons donc avoir besoin d'un connecteur 4 broches mâle à 5 broches femelle.   

Done! :)))
On utilise qlc sur le raspberry pi pour transformer le signal arcnet en signal dmx. ⁾)
